#   Licensed to the Apache Software Foundation (ASF) under one or more
#   contributor license agreements. See the NOTICE file distributed with
#   this work for additional information regarding copyright ownership.
#   The ASF licenses this file to You under the Apache License, Version 2.0
#   (the "License"); you may not use this file except in compliance with
#   the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

version: 2.1
orbs:
  maven: circleci/maven@0.0.7
working_directory: ~/commons-vfs2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: build
                command: mvn -e -X -pl commons-vfs2 -Dchangelist=.ivm.{{ .Environment.CIRCLE_BUILD_NUM }} -Dgpg.skip -Dmaven.test.skip=true -Ddoclint=none -Dbintray.repository=release -Dbintray.serverId=bintray-international-vending-machines-maven -Dbintray.subject=international-vending-machines  clean package com.carrotgarden.maven:bintray-maven-plugin:1.3.20180612164212:deploy
## id::layout::url
#  # -DaltReleaseDeploymentRepository=bintray-international-vendig-machines-maven::default::https://api.bintray.com/maven/international-vendig-machines/maven/commons-vfs2/;publish=1
##  -DaltReleaseDeploymentRepository
#
# #     - run: mvn dependency:go-offline
#
#  #    - save_cache:
#  #        paths:
#            - ~/.m2
#          key: lottery-{{ checksum "pom.xml" }}
#
#      - run: mvn package
#
#      - store_test_results:
#          path: target/surefire-reports
#  #
#  #    - store_artifacts:
#  #          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

workflows:
  version: 2
  build:
    jobs:
      - build

